services:
  - name: elibrary-web
    type: web
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r requirements.txt
    region: oregon
    startCommand: gunicorn elibrary.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_H5wszTpZiW3a@ep-morning-union-ahzk3wvm-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: CORS_ALLOWED_ORIGINS
        value: https://bugema-e-library.vercel.app,http://localhost:5174,http://localhost:3000
